repos:
  # Python code formatting (auto-fixes)
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  # Import sorting (auto-fixes)
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Check for merge conflicts
      - id: check-merge-conflict

      # Check for debugger imports
      - id: debug-statements

      # Check for trailing whitespace
      - id: trailing-whitespace

      # Check for files ending with newline
      - id: end-of-file-fixer

      # Check for YAML syntax
      - id: check-yaml

      # Check for JSON syntax
      - id: check-json

      # Check for private keys
      - id: detect-private-key

  # File formatting (auto-fixes) - excluding markdown
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, json]
        args: [--log-level=warn]
