site_name: Gradio MCP Server Builder
site_description: A CLI tool to automatically build MCP (Model Context Protocol) servers with Gradio from Python function files
site_author: Julien Simon
site_url: https://github.com/juliensimon/gradio-mcp-server-builder

repo_name: juliensimon/gradio-mcp-server-builder
repo_url: https://github.com/juliensimon/gradio-mcp-server-builder
edit_uri: edit/main/docs/

theme: readthedocs

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Basic Usage: getting-started/basic-usage.md
  - User Guide:
    - Input File Format: user-guide/input-format.md
    - Command Line Options: user-guide/command-line.md
    - Code Parsing and Analysis: user-guide/code-parsing.md
    - Docstrings and MCP Tool Discovery: user-guide/docstrings.md
    - Agent Client Guide: user-guide/agent-client.md
    - Testing Guide: user-guide/testing.md
  - Configuration:
    - Overview: configuration/overview.md
    - Model Configuration: configuration/model.md
